#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : irqbalance
Version  : 1.4.0
Release  : 10
URL      : https://github.com/Irqbalance/irqbalance/archive/v1.4.0.tar.gz
Source0  : https://github.com/Irqbalance/irqbalance/archive/v1.4.0.tar.gz
Source1  : irqbalance.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: irqbalance-bin
Requires: irqbalance-config
Requires: irqbalance-autostart
Requires: irqbalance-license
Requires: irqbalance-man
BuildRequires : numactl-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcap-ng)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(ncursesw)

%description
What is Irqbalance
==================
Irqbalance is a daemon to help balance the cpu load generated by interrupts
across all of a systems cpus.  Irqbalance identifies the highest volume
interrupt sources, and isolates them to a single unique cpu, so that load is
spread as much as possible over an entire processor set, while minimizing cache
miss rates for irq handlers.

%package autostart
Summary: autostart components for the irqbalance package.
Group: Default

%description autostart
autostart components for the irqbalance package.


%package bin
Summary: bin components for the irqbalance package.
Group: Binaries
Requires: irqbalance-config
Requires: irqbalance-license
Requires: irqbalance-man

%description bin
bin components for the irqbalance package.


%package config
Summary: config components for the irqbalance package.
Group: Default

%description config
config components for the irqbalance package.


%package license
Summary: license components for the irqbalance package.
Group: Default

%description license
license components for the irqbalance package.


%package man
Summary: man components for the irqbalance package.
Group: Default

%description man
man components for the irqbalance package.


%prep
%setup -q -n irqbalance-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530996355
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1530996355
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/irqbalance
cp COPYING %{buildroot}/usr/share/doc/irqbalance/COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/irqbalance.service
## make_install_append content
mkdir %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../irqbalance.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/irqbalance.service
## make_install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/irqbalance.service

%files bin
%defattr(-,root,root,-)
/usr/bin/irqbalance
/usr/bin/irqbalance-ui

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/irqbalance.service
/usr/lib/systemd/system/irqbalance.service

%files license
%defattr(-,root,root,-)
/usr/share/doc/irqbalance/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/irqbalance.1
